import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html style={{ margin: 0, padding: 0, width: '100%', height: '100%' }}>
      <body style={{ margin: 0, padding: 0, width: '100%', height: '100%', overflow: 'hidden' }}>{children}</body>
    </html>
  );
}
